---
title: C6322
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C6322
helpviewer_keywords:
- C6322
ms.assetid: fb23d2b1-b2a0-465c-8bf5-ec039c6c7757
author: mikeblome
ms.author: mblome
manager: markl
ms.workload:
- multiple
ms.openlocfilehash: d25c37fbfedcfea47c5065da2df28fd115a3f6e3
ms.sourcegitcommit: 5f6ad1cefbcd3d531ce587ad30e684684f4c4d44
ms.translationtype: MT
ms.contentlocale: de-DE
ms.lasthandoff: 10/22/2019
ms.locfileid: "72746311"
---
# <a name="c6322"></a>C6322
Warnung C6322: leerer _except-Block

 Diese Meldung gibt an, dass kein Code im _except-Block vorhanden ist. Folglich k√∂nnen Ausnahmen nicht behandelt werden.

## <a name="example"></a>Beispiel
 Der folgende Code generiert diese Warnung:

```
#include <stdio.h>
#include <excpt.h>
#include <windows.h>

void fd(char *pch)
{
   __try
     {
       // exception rasied if pch is null
       *pch= 0 ;
     }
   __except(GetExceptionCode() == EXCEPTION_ACCESS_VIOLATION)
     {
     }
}
```

 So korrigieren Sie die Warnung unter Verwendung des folgenden Codes

```
#include <stdio.h>
#include <excpt.h>
#include <windows.h>

void f(char *pch)
{
   __try
     {
       // exception rasied if pch is null
      *pch= 0 ;
     }
   __except(GetExceptionCode() == EXCEPTION_ACCESS_VIOLATION ?
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)
     {
       // code to handle exception
       puts("Exception Occurred");
     }
}
```

## <a name="see-also"></a>Siehe auch
 [try-except-Anweisung](/cpp/cpp/try-except-statement)
